blog_title = "Squirrel"
blog_description = "No Bullshit Static Blogging"
blog_theme = "bootstrap"
plugins = [
    "dummy_plugin_for_squirrel"
]

metadata_file = "metadata.toml"
index_file = "index.html"
path_to_generated_content = "generated_content/"
path_to_articles = "articles/"
path_to_themes = "themes/"
path_to_theme_static = "static/"
path_to_generated_static = "static/"
required_keys_in_article = [
    "title",
    "slug",
    "created",
    "content_path"
]
forbidden_keys_in_article = [
    "raw_content",
    "content"
]
server_port = 8000
name_for_injection_callable = "inject_middlewares"
