site_title = "Squirrel"
site_description = "No Bullshit Static Blogging"

plugins = [
    "fs_reader_for_squirrel",
    "auto_slugify_for_squirrel",
    "markdown_for_squirrel",
    "jinja2_templating_for_squirrel",
    "index_renderer_for_squirrel",
    "pages_renderer_for_squirrel",
    "fs_cleaner_for_squirrel",
    "fs_writer_for_squirrel"
]

metadata_file = "metadata.toml"
index_file = "index.html"
build_dir = "test_build/"
source_dir = "test_source/"
theme_dir = "themes/lanyon/"
dir_for_source_static = "static/"
dir_for_build_static = "static/"

required_keys_in_page = [
    "title",
    "content_path"
]

name_for_injection_callable = "inject_middlewares"
