site_title = "Squirrel"
site_description = "No Bullshit Static Blogging"
site_theme = "lanyon"

plugins = [
    "fs_reader_for_squirrel",
    "markdown_for_squirrel",
    "clean_command_for_squirrel",
    "jinja2_templating_for_squirrel",
    "generate_command_for_squirrel"
]

metadata_file = "metadata.toml"
index_file = "index.html"
build_dir = "test_build/"
source_dir = "test_source/"
themes_dir = "themes/"
dir_for_source_static = "static/"
dir_for_build_static = "static/"

required_keys_in_page = [
    "title",
    "slug",
    "created",
    "content_path"
]

name_for_injection_callable = "inject_middlewares"
